//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pzpp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ping
    {
        public System.Guid ID { get; set; }
        public bool Response { get; set; }
        public Nullable<System.DateTimeOffset> Time { get; set; }
    
        public virtual Devices Devices { get; set; }
    }
}
